import Wrapper from "@/components/Wrapper/Wrapper";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Trandy Heaven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
