// "use client"
import Wrapper from "@/components/Wrapper/Wrapper";
import "bootstrap/dist/css/bootstrap.min.css";
import { store } from '@/store/store'
import { Provider } from 'react-redux'

// export const metadata = {
//   title: "Trandy Heaven",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper>{children}</Wrapper>
        {/* <Provider store={store}>
          {children}
        </Provider> */}
      </body>
    </html>
  );
}
